### ISSUE TITLE
Compatibility with Aoe_JsCssTstamp

### ISSUE THREAD

**Issue by paales** [azurams/Magento-Minify#2]
https://github.com/fbrnc/Aoe_JsCssTstamp

Currently while loading a page while the compressor is enabled I'm getting the following error:

```
Error while merging css files to path: css/5846481115f93c6b3845291e26d8af93.1348663533.css
```

The log returns the following:

```
2012-09-26T13:01:19+00:00 ERR (default, 1.555023s, 127.0.0.1): GET:/ - FILE: app/code/community/WBL/Minify/Helper/Core/Data.php:172

exception 'Exception' with message 'No content found in files:
skin/frontend/base/default/css/styles-ie8.css' in app/code/community/WBL/Minify/Helper/Core/Data.php:157
Stack trace:
#0 app/code/local/Aoe/JsCssTstamp/Model/Package.php(134): WBL_Minify_Helper_Core_Data->mergeFiles(Array, '/Users/paales/S...', false, Array, 'css')
#1 [internal function]: Aoe_JsCssTstamp_Model_Package->getMergedCssUrl(Array)
#2 app/code/core/Mage/Page/Block/Html/Head.php(265): call_user_func(Array, Array)
#3 app/code/core/Mage/Page/Block/Html/Head.php(202): Mage_Page_Block_Html_Head->_prepareStaticAndSkinElements('<link rel="styl...', Array, Array, Array)
#4 app/code/local/Aoe/JsCssTstamp/Block/Head.php(20): Mage_Page_Block_Html_Head->getCssJsHtml()
#5 app/design/frontend/base/default/template/page/html/head.phtml(42): Aoe_JsCssTstamp_Block_Head->getCssJsHtml()
#6 app/code/core/Mage/Core/Block/Template.php(241): include('/Users/paales/S...')
#7 app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/base/d...')
#8 app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#9 app/code/core/Mage/Core/Block/Abstract.php(864): Mage_Core_Block_Template->_toHtml()
#10 app/code/core/Mage/Core/Block/Abstract.php(583): Mage_Core_Block_Abstract->toHtml()
#11 app/code/core/Mage/Core/Block/Abstract.php(527): Mage_Core_Block_Abstract->_getChildHtml('head', true)
#12 app/design/frontend/feelgoodies/default/template/page/3columns.phtml(35): Mage_Core_Block_Abstract->getChildHtml('head')
#13 app/code/core/Mage/Core/Block/Template.php(241): include('/Users/paales/S...')
#14 app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/feelgo...')
#15 app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#16 app/code/core/Mage/Core/Block/Abstract.php(864): Mage_Core_Block_Template->_toHtml()
#17 app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#18 app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#19 app/code/core/Mage/Cms/Helper/Page.php(137): Mage_Core_Controller_Varien_Action->renderLayout()
#20 app/code/core/Mage/Cms/Helper/Page.php(52): Mage_Cms_Helper_Page->_renderPage(Object(JR_CleverCms_Cms_IndexController), '1')
#21 app/code/community/JR/CleverCms/Helper/Cms/Page.php(13): Mage_Cms_Helper_Page->renderPage(Object(JR_CleverCms_Cms_IndexController), '1')
#22 app/code/community/JR/CleverCms/controllers/Cms/IndexController.php(14): JR_CleverCms_Helper_Cms_Page->renderPage(Object(JR_CleverCms_Cms_IndexController), '1')
#23 app/code/core/Mage/Core/Controller/Varien/Action.php(419): JR_CleverCms_Cms_IndexController->indexAction()
#24 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#25 app/code/local/Ho/OfflineMaintenance/Controller/Router/Standard.php(54): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#26 app/code/core/Mage/Core/Controller/Varien/Front.php(176): Ho_OfflineMaintenance_Controller_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#27 app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#28 app/Mage.php(683): Mage_Core_Model_App->run(Array)
#29 index.php(87): Mage::run('', 'store')
#30 {main}
```

That file indeed didn't exist, after deleting the reference, everything worked, but it could be handled a little bit more elegantly (not crashing the entire website).

**Comment by nagaraj2501** [comment]
I want solution for this issue.

**Comment by nagaraj2501** [comment]
Please anyone help to me..

**Comment by nagaraj2501** [comment]
Why this exception.log create..?

**Comment by nagaraj2501** [comment]
Please help me,i need solution..
